[package]
name    = "encoding-size"
version = "0.1.0"
edition = "2021"

[dependencies]
minicbor   = { version = "0.13.2", features = ["std", "derive"] }
rand       = "0.8"
serde      = { version = "1.0", features = ["derive"] }
serde_bare = "0.5.0"

